# Generated by Django 6.0.5 on 2026-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_methods',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(default=0),
        ),
    ]
