# Generated by Django 6.0.5 on 2026-05-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_payment_methods_booking_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(default=0),
        ),
    ]
