# Generated by Django 6.0.4 on 2026-05-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_booking_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
