# Generated by Django 6.0.4 on 2026-05-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_flight_flight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(default='A1', max_length=10),
        ),
    ]
